### ISSUE TITLE
Blocking code in async context

### ISSUE THREAD

**Issue by thunderstorm010** [tarkah/iced_gif#1]
https://github.com/tarkah/iced_gif/blob/fca8fb186ed88b9a8465c099a1b6976889e72f06/src/widget/gif.rs#L72

Here, a blocking `BufReader` and a blocking `File` is used. Instead of these, this library should switch to:

a) https://docs.rs/futures/latest/futures/io/struct.BufReader.html
b) https://docs.rs/async-std/latest/async_std/fs/struct.File.html / https://docs.rs/tokio/latest/tokio/fs/struct.File.html

And for the actual Frames implementation, another implementation taking an `AsyncRead` instance would also be required.

**Comment by tarkah** [comment]
Yup! Will need to feature flag a few different implementations to match iced's available executors.
